### PR TITLE
Update Voltha script with multiple BBSim capabilities (VOL-2621)

### PR DESCRIPTION
**Pull request by uottremb**
expand the script to startup up to 10 instances of BBSIM

### CODE REVIEW

**Comment by uottremb** [comment]
Hello ? anybody at home ?

**Comment by davidkbainbridge** [comment]
> Hello ? anybody at home ?

Sorry. I didn't see the notice in my email until you posted this message. Not sure why. I am on PTO today, but will try to look at this tonight.

**Comment by davidkbainbridge** [comment]
please add `NUM_OF_BBSIM` to the option list `ALL_OPTIONS` so that it will be written to the `*-env.sh` file with the rest of the options.

**Comment by uottremb** [comment]
git not my favorite tool, hopefully all is fine now.

**Comment by davidkbainbridge** [comment]
it has been merged, thank you for the contribution.

**Comment by teone** [comment]
@uottremb this feature is not currently working. When you install `kind-voltha` with `NUM_OF_BBSIM=3` all the BBSim instances are started with
```
Command:
      /app/bbsim
      -olt_id
      0
```
that won't work as the 3 OLTs will have the same serial number.

We need to install the BBSim chart by specifying a different `olt_id` parameter and that will need to be addressed in this loop:
```
for instance in $(seq 0 $(($NUM_OF_BBSIM-1))); do
        if [ $instance -eq 0 ]; then
            instance_num=""
        else
            instance_num=$instance
        fi
        if [ $(helm list --deployed --short --namespace voltha "^bbsim${instance_num}\$" | wc -l) -ne 1 ]; then
            espin - $NOT_VERIFIED
            helm_install - voltha bbsim${instance_num} $VOLTHA_BBSIM_CHART $VOLTHA_BBSIM_CHART_VERSION "Install BBSIM${instance_num}"
        else
            espin - $VERIFIED
        fi
    done
```

**Comment by davidkbainbridge** [comment]
i would argue that overriding the values with `olt_id` value set is likely the better solution. It looks like from the helm chart that this is an option.

**Comment by teone** [comment]
@dbainbri-ciena yeah what I meant was to pass `--set olt_id=$instance` to the `helm install` command

**Comment by davidkbainbridge** [comment]
working on patchset now

**Comment by davidkbainbridge** [comment]
merged patchset in

**Pull request merged**
